# Deployment for Ktor application.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: krud-deployment
  namespace: krud-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: krud
  template:
    metadata:
      labels:
        app: krud
    spec:
      containers:
        - name: krud
          image: krud-image:latest
          ports:
            - containerPort: 8080
            - containerPort: 8443
            - containerPort: 5005
          env:
            - name: JAVA_OPTS
              value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
            - name: KRUD_KTOR_SECURITY_SSL_KEY_STORE
              value: "/app/keystore.p12"
